---
- hosts: all
  connection: local
  gather_facts: false 
  tasks:
    - name: Print out server
      debug: msg="{{groups}}"
      run_once: true
    - name: print server
      debug: msg="{{play_hosts}}"
      run_once: true
