---
- hosts: ossl 
  gather_facts: false 
  tasks:
    - name: Print out groups
      debug: var={{group_names}}
      
    - name: Print out all servers
      debug: msg="{{item}} - {{inventory_hostname}}"
      with_items: "{{group_names}}"
