---
- name: Test When family
  hosts: all
  gather_facts: false
  tasks:
    - name: Print out uname when its a debian system
      shell: uname -a
      when: ansible_os_family == "Debian"
      register: the_stuff

    - name: print it
      debug: var=the_stuff
